from collections.abc import Sequence
from typing import Protocol

from app.contracts.provenance import Provenance
from app.schools.contracts import MapBounds
from app.schools.identity_contracts import (
    CanonicalSchoolRecord,
    IdentityMatchField,
    OfficialSchoolListQuery,
)


class SchoolIdentityPort(Protocol):
    def validate(self) -> bool: ...
    def snapshot_id(self) -> str: ...
    def provenance(self) -> Provenance: ...
    def lookup(
        self, field: IdentityMatchField, value: str
    ) -> CanonicalSchoolRecord | None: ...
    def list_official_schools(
        self, query: OfficialSchoolListQuery
    ) -> tuple[tuple[CanonicalSchoolRecord, ...], int, int, tuple[int, ...]]: ...


class DataAccessPort(Protocol):
    def validate(self) -> bool: ...
    def list_schools(self, *, limit: int = 100, offset: int = 0) -> Sequence[dict[str, object]]: ...
    def aggregate(self, asset: str, measure: str, operation: str) -> float | None: ...
    def series(
        self, asset: str, period: str, measure: str, *, school_id: str | None = None
    ) -> Sequence[dict[str, object]]: ...
    def snapshot_id(self) -> str: ...
    def manifest(self) -> dict[str, object]: ...
    def available_cres(self) -> Sequence[int]: ...
    def map_coverage(
        self, *, cre: int | None = None, bounds: MapBounds | None = None
    ) -> dict[str, int | float]: ...
    def school_map_rows(
        self,
        *,
        cre: int | None = None,
        bounds: MapBounds | None = None,
        limit: int = 2000,
        offset: int = 0,
    ) -> Sequence[dict[str, object]]: ...
    def school_profile(self, school_id: str) -> dict[str, object] | None: ...
    def analytics_snapshot(
        self,
        *,
        cre: int | None = None,
        school_id: str | None = None,
        turma_id: str | None = None,
    ) -> Sequence[dict[str, object]]: ...
    def analytics_quality(
        self, *, cre: int | None = None
    ) -> Sequence[dict[str, object]]: ...
    def school_turma_rows(self, school_id: str) -> Sequence[dict[str, object]]: ...
    def skill_matrix_rows(
        self, school_id: str, period: str | None
    ) -> Sequence[dict[str, object]]: ...
